config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'presearch', to: 'profiles#presearch', as: :presearch
  get 'profiles/search', to: 'profiles#search', as: :profile_search
  patch 'myprofile', to: 'profiles#update', as: :myprofile_update
  get 'myprofile', to: 'profiles#myprofile', as: :myprofile
  get 'profile/develop_hard', to: 'profiles#develop_hard', as: :develop_hard
  get 'profile/develop_soft', to: 'profiles#develop_soft', as: :develop_soft
  get 'profile/develop_key', to: 'profiles#develop_key', as: :develop_key
  get 'vacancies/search', to: 'vacancies#search', as: :vacancy_search
  get 'myprofile/edit_user_skills', to: 'profiles#edit_user_skills', as: :edit_user_skills
  patch 'myprofile/update_user_skills', to: 'profiles#update_user_skills', as: :update_user_skills
  get 'myprofile/edit_develop_skills', to: 'profiles#edit_develop_skills', as: :edit_develop_skills
  patch 'myprofile/update_develop_skills', to: 'profiles#update_develop_skills', as: :update_develop_skills

  post 'message/update', to: 'messages#update_message'

  resources :profiles, only: [:index, :show, :edit, :update]

  resources :vacancies, only: [:index, :show]

  resources :conversations, only: [:index, :create, :show] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :user

  has_many :vacancy_skills
  has_many :preferred_skills
  has_many :skills, through: :vacancy_skills
  # has_many :conversations

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :department, presence: true
  validates :start_date, presence: true
  validates :location, presence: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_users, only: [:show]
  after_action :authenticate_user!

  def search
    @user = current_user
    authorize @user
    @pre_selected = params[:skills_ids].map if params[:skills_ids]
    @all_skills = Skill.all
    @hard_skills = Skill.where(skill_type: 'hard')
    @soft_skills = Skill.where(skill_type: 'soft')
    @key_experience = Skill.where(skill_type: 'experience')
    @vacancies = Vacancy.where(department: @user.department)
  end

  def index
    user = current_user
    @skills_to_match = params[:skill_ids].map(&:to_i)
    set_matches
  end

  def show
    @existing_skills = @user.user_skills
    @develop_skills = @user.develop_skills
  end

  def myprofile
    @user = current_user
    authorize @user
    @existing_skills = @user.user_skills
    @develop_skills = @user.develop_skills
  end

  def update
    @user = current_user
    authorize @user
    @user.update(user_params)
    redirect_to myprofile_path
  end

  def edit_user_skills
    @user = current_user
    authorize @user
    @pre_selected = params[:skills_ids] if params[:skills_ids]
    @all_skills = Skill.all
    @hard_skills = Skill.where(skill_type: 'hard')
    @soft_skills = Skill.where(skill_type: 'soft')
    @key_experience = Skill.where(skill_type: 'experience')
  end

    def update_user_skills
    @user = current_user
    authorize @user
    # @pre_selected = params[:skills_ids].map if params[:skills_ids]
    # @all_skills = Skill.all
    # @hard_skills = Skill.where(skill_type: 'hard')
    # @soft_skills = Skill.where(skill_type: 'soft')
    # @key_experience = Skill.where(skill_type: 'experience')
    # @user.user_skills.update(@pre_selected)
    @user.user_skills.destroy_all
    params[:skill_ids].each do |skill_id|
      @user.user_skills << UserSkill.create(user: @user, skill: Skill.find(skill_id))
    end
    redirect_to myprofile_path
  end

  def edit_develop_skills
    @user = current_user
    authorize @user
    @pre_selected = params[:skills_ids].map if params[:skills_ids]
    @all_skills = Skill.all
    @hard_skills = Skill.where(skill_type: 'hard')
    @soft_skills = Skill.where(skill_type: 'soft')
  end

  def update_develop_skills
    @user = current_user
    authorize @user
    # @pre_selected = params[:skills_ids].map if params[:skills_ids]
    # @all_skills = Skill.all
    # @hard_skills = Skill.where(skill_type: 'hard')
    # @soft_skills = Skill.where(skill_type: 'soft')
    # @key_experience = Skill.where(skill_type: 'experience')
    # @user.user_skills.update(@pre_selected)
    @user.develop_skills.destroy_all
    params[:skill_ids].each do |skill_id|
      @user.develop_skills << DevelopSkill.create(user: @user, skill: Skill.find(skill_id))
    end
    redirect_to myprofile_path
  end

  private

  def set_matches
    @matches = []
    # Have
    users = policy_scope(User).order(created_at: :desc)
    users.each do |user|
      skills = user.user_skills.pluck(:skill_id)
      is_match = (@skills_to_match & skills).any?
      @matches << user if is_match
    end

    # Develop
    users.each do |user|
      skills = user.develop_skills.pluck(:skill_id)
      is_match = (@skills_to_match & skills).any?
      @matches << user if is_match
    end

    @matches = @matches.uniq
    @matches.sort_by! do |match|
      match.user_skills.select {|user_skill| @skills_to_match.include?(user_skill.skill_id) }.length
    end
  end

  def set_users
    @user = User.find(params[:id])
    authorize @user
  end

  def user_params
    params.require(:user).permit(:description)
  end

  def edit_user_skills_params
    params.require(:skill_ids).permit(:user_skill_ids)
  end
end

app/views/profiles/edit_develop_skills.html.erb
<div class="container">
  <div class="search-result-h1">
    <h1>WHICH SKILLS DO YOU WANT TO DEVELOP?</h1>
    <p>Let managers know your interests!</p>
  </div>
  <!-- Main body -->

  <div class="lower-search-container">

    <!-- left side -->

    <div class="skill-container">
      <div class="skill-cat-container-to-develop">
        <button class="cat-btn cat-btn-active" data-value="all">All</button>
        <button class="cat-btn" data-value="hard">HARD SKILLS</button>
        <button class="cat-btn" data-value="soft">SOFT SKILLS</button>
      </div>


      <!-- main form start-->

    <%= form_tag("/myprofile/update_develop_skills", method: "patch") do  %>

      <!-- hard skills -->

      <div class="skill-card" id="hard">
        <div class="d-flex justify-content-between">
          <h3>HARD SKILLS</h3>
          <i class="fas fa-eraser" id="clear-hard"></i>
        </div>
        <div class="skills-grid">
          <% @hard_skills.each do |skill| %>
              <%= check_box_tag "skill_ids[]", skill.id, nil, id: "skill-item-#{skill.id}", class: 'hidden'%>
              <label for="<%= "skill-item-#{skill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
           url('<%= cl_image_path skill.photo, height: 120, width: 120, crop: :fill %>');">
                <div class="section">
                  <p class="show-profile"><%= skill.name %></p>
                  <!-- Popover -->
                    <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                    data-popover-content="#myPopoverContent<%=skill.id%>"><i class="fas fa-info-circle"></i></a>

                    <!-- Content for Popover: -->
                    <div id="myPopoverContent<%=skill.id%>" style="display:none">
                      <div class="skill-info">
                        <h2><%= skill.name %></h2>
                        <p><%= skill.description %></p>
                      </div>
                    </div>
                  <div class="overlay">
                  </div>
                </div>
              </label>
          <% end %>
        </div>
      </div>


      <!-- soft skills -->

      <div class="skill-card" id="soft">
        <div class="d-flex justify-content-between">
          <h3>SOFT SKILLS</h3>
          <i class="fas fa-eraser" id="clear-soft"></i>
        </div>
        <div class="skills-grid">

          <% @soft_skills.each do |skill| %>
              <%= check_box_tag "skill_ids[]", skill.id, nil, id: "skill-item-#{skill.id}", class: 'hidden'%>
              <label for="<%= "skill-item-#{skill.id}" %>" class="skill-grid-item checkbox soft" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
           url('<%= cl_image_path skill.photo, height: 120, width: 120, crop: :fill %>')">
                <div class="section">
                  <p class="show-profile"><%= skill.name %></p>
                  <!-- Popover -->
                    <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                    data-popover-content="#myPopoverContent<%=skill.id%>"><i class="fas fa-info-circle"></i></a>

                    <!-- Content for Popover: -->
                    <div id="myPopoverContent<%=skill.id%>" style="display:none">
                      <div class="skill-info">
                        <h2><%= skill.name %></h2>
                        <p><%= skill.description %></p>
                      </div>
                    </div>
                  <div class="overlay">
                  </div>
                </div>
              </label>
          <% end %>
        </div>
      </div>





    <!-- right side -->
  </div>
    <div class="job-select-container">

      <div class="selection-container">
        <div class="d-flex justify-content-between">
          <h4>SELECTION</h4>
          <i class="fas fa-eraser" id="clear-all"></i>
        </div>
        <div class="d-flex flex-wrap job-name-container">
          <div id="selection-collection"></div>
        </div>
        <!-- <div class="d-flex justify-content-center"> -->
          <%= submit_tag "SAVE", class: 'search-btn' %>
          <% end %>
        <!-- </div> -->
        <!-- main form end -->
        <%= link_to :back do %>
          <div class="search-btn cancel-btn">CANCEL</div>
        <% end %>
      </div>
    </div>
</div>

<!-- hidden array for adding skills -->
<% if @pre_selected %>
  <ul class="hidden">
  <% @pre_selected.each do |skill| %>
    <li value="<%= skill %>" class="hidden-skill"></li>\
  <% end %>
  </ul>
<% end %>
</div>

app/views/profiles/index.html.erb
<div class="container">

  <div class="search-result-h1">
    <h1>LOOKING FOR A CANDIDATE</h1>
  </div>

  <h3 class="search-result-title-h3">Your Selection</h3>
  <div class="selected-skills-result">
    <% @skills_to_match.each do |selected_skill| %>
    <p class="skill-selection"><%= Skill.find(selected_skill).name %></p>
    <% end %>
    <%= link_to "+", profile_search_path(skills_ids: @skills_to_match), class: "edit-plus" %>
  </div>

  <h2 class="search-result-title-h2">Matching profiles</h2>


  <% @matches.reverse.first(7).each do |user| %>
  <% unless user == current_user || user.first_name == "Astrid" %>
  <%= link_to profile_path(user.id) do %>
  <div class="container-custom">
    <div class="row">
      <div class="col-12 col-sm-4">
        <div class="employee-detail-all">
          <div class="employee-detail">
            <%= cl_image_tag user.photo, height: 300, width: 300, crop: :fill, class: "avatar-big" %>
            <div class="employee-contact">
              <h2><%= user.first_name.capitalize %> <%= user.last_name.upcase %></h2>
              <h3><%= user.job_title %></h3>
              <p><%= user.location %></p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-4">
        <div class="employee-have-skills-all">
          <div class="employee-have-skills">
            <h3>Existing skills</h3>
            <div class="employee-skills">
              <% if user.user_skills.select {|user_skill| @skills_to_match.include?(user_skill.skill_id) }.empty? %>
                  <p id="others">Other skills than selected...</p>
                <% else %>
              <% user.user_skills.select {|user_skill| @skills_to_match.include?(user_skill.skill_id) }.each do |user_skill| %>
              <p class="skill-selection"><%= user_skill.skill.name %></p>
              <% end %>
              <% end %>

            </div>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-4">
        <div class="employee-wish-skills-all">
          <div class="employee-wish-skills">
            <h3>Wish to develop</h3>
            <% if user.develop_skills.select {|user_skill| @skills_to_match.include?(user_skill.skill_id) }.empty? %>
              <p id="others">Other skills than selected...</p>
            <% else %>
              <div class="employee-skills">
                <% user.develop_skills.select {|user_skill| @skills_to_match.include?(user_skill.skill_id) }.each do |user_skill| %>
                  <p class="skill-selection"><%= user_skill.skill.name %></p>
                <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% end %>
  <% end %>
</div>

app/views/profiles/myprofile.html.erb
<div class="blue-banner"></div>

<div class="container">
<!-- title box -->
  <div class="myprofile-container">
    <%= link_to :back, class: 'link_absolute' do %>
      <i class="fas fa-chevron-left"></i>Back
    <% end %>
    <div class="d-flex align-items-center">
      <div class="myprofile-image">
        <%= cl_image_tag @user.photo, height: 300, width: 300, crop: :fill %>
      </div>
      <div class="myprofile-name">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      </div>
    </div>
  </div>

<div class="d-flex">
  <div class="box-profile">

      <!-- description box -->

        <div class="myprofile-info-container">
          <div class="myprofile-info-card">
            <div class="d-flex justify-content-between">
              <h2><%= @user.job_title %></h2>
              <i class="fas fa-edit" id="edit-description"></i>
            </div>
            <div class="info-employee">
              <ul class="info-employee-label">
                <li>Department - <%= @user.department %></li>
                <li>Location - <%= @user.location %></li>
              </ul>
            </div>
            <div id="description" class="toggle-div display-block">
            <p><%= @user.description %></p>
          </div>
          <div id="description-form" class="toggle-div">
            <%= simple_form_for(current_user, url: myprofile_path(@user), html: { method: :patch }) do |f| %>
           <%= f.input :description, as: :text, label: false, placeholder: 'Tell us what others need to know' %>
           <%= f.button :submit, "SAVE", class: "button"%>
           <% end %>
         </div>
        </div>
      </div>

      <!-- key experiences -->

        <div class="myprofile-skill-card" id="key">
          <div class="d-flex justify-content-between">
            <h3>KEY EXPERIENCES</h3>
            <% param_skills = @existing_skills.map {|s| s.skill_id} %>
            <%= link_to edit_user_skills_path(skills_ids: param_skills) do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </div>

          <div class="skills-grid-1">
            <% @existing_skills.each do |eskill| %>
            <% if eskill.skill.skill_type == "experience" %>
                <label for="<%= "skill-item-#{eskill.id}" %>" class="skill-grid-item checkbox key" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
             url('<%= cl_image_path eskill.skill.photo, height: 300, width: 300, crop: :fill %>')">

                  <div class="section">
                    <p class="show-profile"><%= eskill.skill.name %></p>
                    <div class="overlay">
                    </div>
                  </div>
                </label>
                <% end %>
            <% end %>
          </div>
        </div>

      <!-- Hard Skills -->

        <div class="myprofile-skill-card" id="hard">
          <div class="d-flex justify-content-between">
            <h3>EXISTING SKILLS</h3>
            <%= link_to edit_user_skills_path(skills_ids: param_skills) do %>
              <i class="fas fa-edit"></i>
            <% end %>
          </div>
          <div class="skills-grid-1">
            <% @existing_skills.each do |uskill| %>
            <% unless uskill.skill.skill_type == "experience" %>
                <label for="<%= "skill-item-#{uskill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
             url('<%= cl_image_path uskill.skill.photo, height: 300, width: 300, crop: :fill %>')">
                  <div class="section">
                    <p class="show-profile"><%= uskill.skill.name %></p>

                      <!-- Popover -->
                        <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                        data-popover-content="#myPopoverContent<%=uskill.id%>"><i class="fas fa-info-circle"></i></a>

                        <!-- Content for Popover: -->
                        <div id="myPopoverContent<%=uskill.id%>" style="display:none">
                          <div class="skill-info">
                            <h2><%= uskill.skill.name %></h2>
                            <p><%= uskill.skill.description %></p>
                          </div>
                        </div>

                    <div class="overlay">
                    </div>
                  </div>
                </label>
                <% end %>
            <% end %>
          </div>
        </div>

        <!-- soft Skills -->
          <div class="myprofile-skill-card" id="hard">
            <div class="d-flex justify-content-between">
              <h3>SKILLS TO DEVELOP</h3>
              <% dev_skills = @develop_skills.map {|s| s.skill_id} %>
              <%= link_to edit_develop_skills_path(skills_ids: dev_skills) do  %>
                <i class="fas fa-edit"></i>
              <% end %>
            </div>
            <div class="skills-grid-1">
              <% @develop_skills.each do |dskill| %>
                  <label for="<%= "skill-item-#{dskill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
               url('<%= cl_image_path dskill.skill.photo, height: 300, width: 300, crop: :fill %>')">
                    <div class="section">
                      <p class="show-profile"><%= dskill.skill.name %></p>

                      <!-- Popover -->
                        <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                        data-popover-content="#myPopoverContent<%=dskill.id%>"><i class="fas fa-info-circle"></i></a>

                        <!-- Content for Popover: -->
                        <div id="myPopoverContent<%=dskill.id%>" style="display:none">
                          <div class="skill-info">
                            <h2><%= dskill.skill.name %></h2>
                            <p><%= dskill.skill.description %></p>
                          </div>
                        </div>

                      <div class="overlay">
                      </div>
                    </div>
                  </label>
              <% end %>
            </div>
          </div>

  </div>

</div>

</div>

app/views/profiles/show.html.erb
<div class="blue-banner"></div>

<div class="container">
<!-- title box -->
  <div class="myprofile-container">
    <%= link_to :back, class: 'link_absolute' do %>
      <i class="fas fa-chevron-left"></i>Back
    <% end %>
    <div class="d-flex align-items-center">
      <div class="myprofile-image">
        <%= cl_image_tag @user.photo, height: 300, width: 300, crop: :fill %>
      </div>
      <div class="myprofile-name">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
      </div>
    </div>
  </div>

  <!-- Message modal -->
  <div id="sendMessageModal<%= @user.id %>" class="modal" data-id="<%= @user.id %>">
    <!-- Modal content -->
    <div class="modal-content<%= @user.id %> modal-content">
      <p><em><%= "Send #{@user.first_name} a message..." %></em></p>
      <%= simple_form_for :conversation, url: conversations_path(user_id: @user.id), remote: true, method: :post, html: { class: "new_message"} do |form| %>
        <%= form.input :content, label: false, input_html: { id: "message-field-#{@user.id}" } %>
        <% form.hidden_field :user_id, value: @user %>
        <div class="d-flex">
          <%= form.button :submit, value: 'send', class: "modal-submit-#{@user.id} modal-submit" %>
        <% end %>
        <div class="modal-cancel-<%= @user.id %> modal-cancel">cancel</div>
        </div>
    </div>
  </div>



<div class="d-flex">
  <div class="box-profile">

      <!-- description box -->

        <div class="myprofile-info-container">
          <div class="myprofile-info-card">
            <div class="d-flex justify-content-between align-items-center">
              <h2><%= @user.job_title %></h2>
              <div class="button btn-message" id="sendBtn<%= @user.id %>">Send message</div>
            </div>
            <div class="info-employee">
              <ul class="info-employee-label">
                <li>Department - <%= @user.department %></li>
                <li>Location - <%= @user.location %></li>
              </ul>
            </div>
            <div>
            <p><%= @user.description %></p>
          </div>
        </div>
      </div>

  <!-- key experiences -->

        <div class="myprofile-skill-card" id="key">
          <div class="d-flex justify-content-between">
            <h3>Key Experiences</h3>

          </div>
          <div class="skills-grid-1">

            <% @existing_skills.each do |eskill| %>
            <% if eskill.skill.skill_type == "experience" %>
                <label for="<%= "skill-item-#{eskill.id}" %>" class="skill-grid-item checkbox key" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
             url('<%= cl_image_path eskill.skill.photo, height: 300, width: 300, crop: :fill %>')">

                  <div class="section">
                    <p class="show-profile"><%= eskill.skill.name %></p>
                    <div class="overlay">
                    </div>
                  </div>
                </label>
                <% end %>
            <% end %>
          </div>
        </div>

  <!-- Hard Skills -->

        <div class="myprofile-skill-card" id="hard">
          <div class="d-flex justify-content-between">
            <h3>Existing skills</h3>

          </div>
          <div class="skills-grid-1">
            <% @existing_skills.each do |uskill| %>
            <% unless uskill.skill.skill_type == "experience" %>
                <label for="<%= "skill-item-#{uskill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
             url('<%= cl_image_path uskill.skill.photo, height: 300, width: 300, crop: :fill %>')">
                  <div class="section">
                    <p class="show-profile"><%= uskill.skill.name %></p>

                      <!-- Popover -->
                        <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                        data-popover-content="#myPopoverContent<%=uskill.id%>"><i class="fas fa-info-circle"></i></a>

                        <!-- Content for Popover: -->
                        <div id="myPopoverContent<%=uskill.id%>" style="display:none">
                          <div class="skill-info">
                            <h2><%= uskill.skill.name %></h2>
                            <p><%= uskill.skill.description %></p>
                          </div>
                        </div>

                    <div class="overlay">
                    </div>
                  </div>
                </label>
                <% end %>
            <% end %>
          </div>
        </div>

  <!-- soft Skills -->

        <div class="myprofile-skill-card" id="hard">
          <div class="d-flex justify-content-between">
            <h3>Wish to develop</h3>
          </div>
          <div class="skills-grid-1">
            <% @develop_skills.each do |dskill| %>
                <label for="<%= "skill-item-#{dskill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
             url('<%= cl_image_path dskill.skill.photo, height: 300, width: 300, crop: :fill %>')">
                  <div class="section">
                    <p class="show-profile"><%= dskill.skill.name %></p>

                    <!-- Popover -->
                      <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                      data-popover-content="#myPopoverContent<%=dskill.id%>"><i class="fas fa-info-circle"></i></a>

                      <!-- Content for Popover: -->
                      <div id="myPopoverContent<%=dskill.id%>" style="display:none">
                        <div class="skill-info">
                          <h2><%= dskill.skill.name %></h2>
                          <p><%= dskill.skill.description %></p>
                        </div>
                      </div>

                    <div class="overlay">
                    </div>
                  </div>
                </label>
            <% end %>
          </div>
        </div>
  </div>
</div>
</div>
</div>