config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'presearch', to: 'profiles#presearch', as: :presearch
  get 'profiles/search', to: 'profiles#search', as: :profile_search
  patch 'myprofile', to: 'profiles#update', as: :myprofile_update
  get 'myprofile', to: 'profiles#myprofile', as: :myprofile
  get 'profile/develop_hard', to: 'profiles#develop_hard', as: :develop_hard
  get 'profile/develop_soft', to: 'profiles#develop_soft', as: :develop_soft
  get 'profile/develop_key', to: 'profiles#develop_key', as: :develop_key
  get 'vacancies/search', to: 'vacancies#search', as: :vacancy_search
  get 'myprofile/edit_user_skills', to: 'profiles#edit_user_skills', as: :edit_user_skills
  patch 'myprofile/update_user_skills', to: 'profiles#update_user_skills', as: :update_user_skills
  get 'myprofile/edit_develop_skills', to: 'profiles#edit_develop_skills', as: :edit_develop_skills
  patch 'myprofile/update_develop_skills', to: 'profiles#update_develop_skills', as: :update_develop_skills

  post 'message/update', to: 'messages#update_message'

  resources :profiles, only: [:index, :show, :edit, :update]

  resources :vacancies, only: [:index, :show]

  resources :conversations, only: [:index, :create, :show] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  # belongs_to :vacancy
  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
      where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    new(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_user(user)
    user == recipient ? sender : recipient
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  skip_after_action :verify_authorized

  def index
    @users = User.all.where.not(id: current_user)
    @conversations = policy_scope(Conversation).where(recipient_id: current_user.id).or(policy_scope(Conversation).where(sender_id: current_user.id))
  end

  def create
    @conversation = Conversation.get(current_user.id, params[:user_id])
    @is_new_conversation = @conversation.id.nil?
    @conversation.save!
    message = Message.new(body: params[:conversation][:content])
    message.conversation = @conversation
    message.user = current_user
    message.save!
    # MessageBroadcastJob.new.perform(message)
    respond_to do |format|
      format.html { redirect_to profile_path(params[:user_id]) }
      format.js
    end
  end

  def show
    @conversation = Conversation.find(params[:id])
    @messages = @conversation.messages.order(id: :asc)
    respond_to do |format|
      format.js
    end
  end
end

app/views/conversations/_conversation.html.erb
<div class="conversation-topper">
  <div class="d-flex">
    <%= cl_image_tag conversation.opposed_user(current_user).photo, height: 70, width: 70, crop: :fill, class: "avatar" %>
    <div><%= conversation.opposed_user(current_user).first_name %></div>
  </div>
  <i class="fas fa-bars convo-top-info dropdown-toggle" id="messageDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
   <div class="dropdown-menu dropdown-menu-right" aria-labelledby="messageDropdown">
  <%= link_to "View profile", profile_path(conversation.opposed_user(current_user)), class: "dropdown-item" %>
</div>
</div>

<% @messages.each do |message| %>
  <% if current_user == message.user %>
    <div class="comment bubble-right" data-message-id="<%= message.id %>">
  <% else %>
    <div class="comment bubble-left" data-message-id="<%= message.id %>">
  <% end %>
    <p><%= message.body %></p>
  </div>
<% end %>

app/views/conversations/_insert_new_conversation.html.erb
<%= link_to conversation_path(conversation), remote: true do %>
  <div class="conversation-box">
      <%= cl_image_tag conversation.opposed_user(current_user).photo, height: 70, width: 70, crop: :fill, class: "avatar" %>
    <div class="conv-box">
      <div class="conv-box-top">
        <p class="conv-user-name"><%=  conversation.opposed_user(current_user).first_name %> <%= conversation.opposed_user(current_user).last_name %></p>
        <p class="conv-time"> <%= conversation.messages.last.created_at.to_time.strftime("%k:%M") %></p>
      </div>
      <p class="conv-preview <%="conv-preview-#{conversation.id}"%>">
        <% if conversation.messages.last.body.length < 25 %>
          <%= conversation.messages.last.body %>
        <% else %>
          <%= conversation.messages.last.body[0..25] %>...
        <% end %>
        </p>
    </div>
  </div>
<% end %>

app/views/conversations/_submit.html.erb
<div class="new-message-container">
  <form class="new_message">
    <input name="conversation_id" type="hidden" value="<%= conversation.id %>">
    <input name="user_id" type="hidden" value="<%= current_user.id %>">
    <div class="message-text-btn">
      <textarea name="body" class="autoExpand typing-area"></textarea>
      <button type="submit" class="fabutton" rows='3' data-min-rows='3' placeholder='type a message...'>
        <i class="fa fa-paper-plane" aria-hidden="true"></i>
      </button>
    </div>
  </form>
</div>

app/views/conversations/index.html.erb
<div class="container">
  <div class="container-conversation" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
    url('<%= image_path "background-hp.jpg" %>');">
    <% if @conversations.length > 0 %>
      <div class="conversation-bar">
        <% @conversations.each do |conversation| %>
          <%= link_to conversation_path(conversation), remote: true do %>
            <% rMessages = conversation.messages.where(user_id: conversation.opposed_user(current_user).id) %>
            <% cClasses = "conversation-box" %>
            <% if rMessages.count > 0 %>
              <% if rMessages.last.read == false %>
                <% cClasses = "conversation-box conversation-box-new" %>
              <% end %>
            <% end %>
            <div class="<%= cClasses %>">
              <%= cl_image_tag conversation.opposed_user(current_user).photo, height: 40, width: 40, crop: :fill, class: "avatar" %>
              <div class="conv-box">
                <div class="conv-box-top">
                  <p class="conv-user-name">
                    <%=  conversation.opposed_user(current_user).first_name %>
                    <%= conversation.opposed_user(current_user).last_name %>
                  </p>
                  <p class="conv-time">
                    <%= conversation.messages.last.created_at.to_time.strftime("%k:%M") %>
                  </p>
                </div>
                <p class="conv-preview <%=" conv-preview-#{conversation.id}"%>">
                  <% if conversation.messages.last.body.length < 25 %>
                    <%= conversation.messages.last.body %>
                  <% else %>
                    <%= conversation.messages.last.body[0..25] %>...
                  <% end %>
                </p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="conv-display-container">
        <div class="conversation-display">
          <h1>Your career. <br>Your skills. <br>Your move...</h1>
        </div>
      </div>
      <% else %>
      <div class="conversation-bar"></div>
        <% if current_user.is_manager %>
          <div class="conversation-display">
            <div>
              <h1>No conversations here yet...</h1>
              <h3>Find the perfect candidate and send a message to get started!</h3>
            </div>
          </div>
          <div class="home-btns">
            <%= link_to 'CANDIDATES', profile_search_path, class: "home-btn-candidate" %>
          </div>
        <% else %>
          <div class="conversation-display">
            <h1>No conversations here yet...</h1>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/conversations/show.js.erb
var displayArea = document.querySelector('.conversation-display');

// code to set messages to read when oping conversartion

<% @conversation.messages.where(user_id: @conversation.opposed_user(current_user).id).each do |message| %>
<% message.read = true %>
<% message.save %>
<% end %>

displayArea.innerHTML = '<%= j render "conversations/conversation", conversation: @conversation %>'
displayArea.insertAdjacentHTML('beforeEnd', '<%= j render "conversations/submit", conversation: @conversation %>')

displayArea.scrollTop = displayArea.scrollHeight;

function submitOnEnter(event){
    if(event.which === 13 && !event.shiftKey){
        elem = event.target.form
        Rails.fire(elem, 'submit');
        event.preventDefault();
    }
}

document.querySelector(".typing-area").addEventListener("keypress", submitOnEnter);