config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'presearch', to: 'profiles#presearch', as: :presearch
  get 'profiles/search', to: 'profiles#search', as: :profile_search
  patch 'myprofile', to: 'profiles#update', as: :myprofile_update
  get 'myprofile', to: 'profiles#myprofile', as: :myprofile
  get 'profile/develop_hard', to: 'profiles#develop_hard', as: :develop_hard
  get 'profile/develop_soft', to: 'profiles#develop_soft', as: :develop_soft
  get 'profile/develop_key', to: 'profiles#develop_key', as: :develop_key
  get 'vacancies/search', to: 'vacancies#search', as: :vacancy_search
  get 'myprofile/edit_user_skills', to: 'profiles#edit_user_skills', as: :edit_user_skills
  patch 'myprofile/update_user_skills', to: 'profiles#update_user_skills', as: :update_user_skills
  get 'myprofile/edit_develop_skills', to: 'profiles#edit_develop_skills', as: :edit_develop_skills
  patch 'myprofile/update_develop_skills', to: 'profiles#update_develop_skills', as: :update_develop_skills

  post 'message/update', to: 'messages#update_message'

  resources :profiles, only: [:index, :show, :edit, :update]

  resources :vacancies, only: [:index, :show]

  resources :conversations, only: [:index, :create, :show] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
end

app/models/vacancy.rb
class Vacancy < ApplicationRecord
  belongs_to :user

  has_many :vacancy_skills
  has_many :preferred_skills
  has_many :skills, through: :vacancy_skills
  # has_many :conversations

  mount_uploader :photo, PhotoUploader

  validates :title, presence: true
  validates :description, presence: true
  validates :department, presence: true
  validates :start_date, presence: true
  validates :location, presence: true
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  before_action :set_vacancies, only: [:show]

  def index
    @vacancies = Vacancy.all
    @skills_to_match = params[:skill_ids].map(&:to_i)
    set_matches
  end

  def show
    @users = User.where(job_title: @vacancy.title)
    @vacancy_skills = @vacancy.vacancy_skills
    @preferred_skills = @vacancy.preferred_skills
  end

  def search
    @user = current_user
    @pre_selected = params[:skills_ids].map if params[:skills_ids]
    @all_skills = Skill.all
    @hard_skills = Skill.where(skill_type: 'hard')
    @soft_skills = Skill.where(skill_type: 'soft')
    @key_experience = Skill.where(skill_type: 'experience')
    @vacancies = Vacancy.where(department: @user.department)
    authorize @vacancies
  end

  private

  def set_matches
    @matches = []
    # Have
    vacancies = policy_scope(Vacancy).order(created_at: :desc)
    vacancies.each do |vacancy|
      skills = vacancy.vacancy_skills.pluck(:skill_id)
      is_match = (@skills_to_match & skills).any?
      @matches << vacancy if is_match
    end

    vacancies.each do |vacancy|
      skills = vacancy.preferred_skills.pluck(:skill_id)
      is_match = (@skills_to_match & skills).any?
      @matches << vacancy if is_match
    end

    @matches = @matches.uniq
    @matches.sort_by! do |match|
      match.vacancy_skills.select {|vacancy_skill| @skills_to_match.include?(vacancy_skill.skill_id) }.length
    end
  end


  def set_vacancies
    @vacancy = Vacancy.find(params[:id])
    authorize @vacancy
  end
end

app/views/vacancies/index.html.erb
<div class="container">

  <div class="search-result-h1">
    <h1>LOOKING FOR A NEW POSITION</h1>
  </div>

  <h3 class="search-result-title-h3">Your Selection</h3>
  <div class="selected-skills-result">
    <% @skills_to_match.each do |selected_skill| %>
      <p class="skill-selection"><%= Skill.find(selected_skill).name %></p>
    <% end %>
    <%= link_to "+", vacancy_search_path(skills_ids: @skills_to_match), class: "edit-plus" %>
  </div>

  <h2 class="search-result-title-h2">Matching positions</h2>


  <% @matches.reverse.first(7).each do |vacancy| %>
  <%= link_to vacancy_path(vacancy.id) do %>
  <div class="container-custom">
    <div class="row">
      <div class="col-12 col-sm-4">
        <div class="employee-detail-all">
          <div class="employee-detail">
            <%= cl_image_tag vacancy.photo, class: "avatar-big" , height: 300, width: 300, crop: :fill %>
            <div class="employee-contact">
              <h2><%= vacancy.title.capitalize %></h2>
              <h3><%= vacancy.department %></h3>
              <p><%= vacancy.location %></p>
            </div>
          </div>
        </div>
      </div>

      <div class="col-12 col-sm-4">
        <div class="employee-have-skills-all">
          <div class="employee-have-skills">
            <h3>Required skills</h3>
              <% if vacancy.vacancy_skills.select {|vacancy_skill| @skills_to_match.include?(vacancy_skill.skill_id) }.empty? %>
                <p id="others">Other skills than selected...</p>
              <% else %>
            <div class="employee-skills">
              <% vacancy.vacancy_skills.select {|vacancy_skill| @skills_to_match.include?(vacancy_skill.skill_id) }.each do |vacancy_skill| %>
              <p class="skill-selection"><%= vacancy_skill.skill.name %></p>
              <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-12 col-sm-4">
        <div class="employee-wish-skills-all">
          <div class="employee-wish-skills">
            <h3>Preferred skills</h3>
            <% if vacancy.preferred_skills.select {|preferred_skill| @skills_to_match.include?(preferred_skill.skill_id) }.empty? %>
              <p id="others">Other skills than selected...</p>
            <% else %>
              <div class="employee-skills">
                <% vacancy.preferred_skills.select {|preferred_skill| @skills_to_match.include?(preferred_skill.skill_id) }.each do |preferred_skill| %>
                  <p class="skill-selection"><%= preferred_skill.skill.name %></p>
                <% end %>
            </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <% end %>
  <% end %>
</div>

app/views/vacancies/search.html.erb
<!-- top skills categories bar -->

<div class="container">
  <div class="search-result-h1">
    <h1>LOOKING FOR A NEW POSITION</h1>
    <p>Your skills, your move... <br>Select the skills you have or want to develop</p>
  </div>


  <!-- Main body -->

  <div class="lower-search-container">

    <!-- left side -->

    <div class="skill-container">
      <div class="skill-cat-container">
        <button class="cat-btn cat-btn-active" data-value="all">All</button>
        <button class="cat-btn" data-value="hard">HARD SKILLS</button>
        <button class="cat-btn" data-value="soft">SOFT SKILLS</button>
        <button class="cat-btn" data-value="key">KEY EXPERIENCES</button>
      </div>

      <!-- main form start-->

      <%= form_tag("/vacancies", method: "get") do  %>

      <!-- hard skills -->

      <div class="skill-card" id="hard">
        <div class="d-flex justify-content-between">
          <h3>HARD SKILLS</h3>
          <i class="fas fa-eraser" id="clear-hard"></i>
        </div>
        <div class="skills-grid">
          <% @hard_skills.each do |skill| %>
              <%= check_box_tag "skill_ids[]", skill.id, nil, id: "skill-item-#{skill.id}", class: 'hidden'%>
              <label for="<%= "skill-item-#{skill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
           url('<%= cl_image_path skill.photo, height: 300, width: 300, crop: :fill %>');">
                <div class="section">
                  <p class="show-profile"><%= skill.name %></p>
                  <!-- Popover -->
                    <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                    data-popover-content="#myPopoverContent<%=skill.id%>"><i class="fas fa-info-circle"></i></a>

                    <!-- Content for Popover: -->
                    <div id="myPopoverContent<%=skill.id%>" style="display:none">
                      <div class="skill-info">
                        <h2><%= skill.name %></h2>
                        <p><%= skill.description %></p>
                      </div>
                    </div>
                  <div class="overlay">
                  </div>
                </div>
              </label>
          <% end %>
        </div>
      </div>


      <!-- soft skills -->

      <div class="skill-card" id="soft">
        <div class="d-flex justify-content-between">
          <h3>SOFT SKILLS</h3>
          <i class="fas fa-eraser" id="clear-soft"></i>
        </div>
        <div class="skills-grid">

          <% @soft_skills.each do |skill| %>
              <%= check_box_tag "skill_ids[]", skill.id, nil, id: "skill-item-#{skill.id}", class: 'hidden'%>
              <label for="<%= "skill-item-#{skill.id}" %>" class="skill-grid-item checkbox soft" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
           url('<%= cl_image_path skill.photo, height: 300, width: 300, crop: :fill %>')">
                <div class="section">
                  <p class="show-profile"><%= skill.name %></p>
                  <!-- Popover -->
                    <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
                    data-popover-content="#myPopoverContent<%=skill.id%>"><i class="fas fa-info-circle"></i></a>

                    <!-- Content for Popover: -->
                    <div id="myPopoverContent<%=skill.id%>" style="display:none">
                      <div class="skill-info">
                        <h2><%= skill.name %></h2>
                        <p><%= skill.description %></p>
                      </div>
                    </div>
                  <div class="overlay">
                  </div>
                </div>
              </label>
          <% end %>
        </div>
      </div>



      <!-- key experiences -->

      <div class="skill-card" id="key">
        <div class="d-flex justify-content-between">
          <h3>KEY EXPERIENCE</h3>
          <i class="fas fa-eraser" id="clear-key"></i>
        </div>
        <div class="skills-grid">

          <% @key_experience.each do |skill| %>
              <%= check_box_tag "skill_ids[]", skill.id, nil, id: "skill-item-#{skill.id}", class: 'hidden'%>
              <label for="<%= "skill-item-#{skill.id}" %>" class="skill-grid-item checkbox key" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
           url('<%= cl_image_path skill.photo, height: 300, width: 300, crop: :fill %>')">
                <div class="section">
                  <p class="show-profile"><%= skill.name %></p>
                  <div class="overlay">
                  </div>
                </div>
              </label>
          <% end %>
        </div>
      </div>

    <!-- right side -->
  </div>
    <div class="job-select-container">
      <div class="vacancies-container">
        <h4>YOUR SKILLS</h4>
          <div class="job-container">
            <p><%= 'Your existing skills' %></p>
            <label class="radio-container">
              <input type="checkbox" name="radio" class="check-box" data-id="<%= current_user.id %>">
              <% current_user.user_skills.each do |skill| %>
                <input type="hidden" class="<%= "job-skills" %> " value="<%= skill.skill_id %>">
              <% end %>
              <span class="checkmark"></span>
            </label>
          </div>
          <div class="job-container">
            <p><%= 'Skills you want to develop' %></p>
            <label class="radio-container">
              <input type="checkbox" name="radio" class="check-box" data-id="<%= current_user.id %>">
              <% current_user.develop_skills.each do |skill| %>
                <input type="hidden" class="<%= "job-skills" %> " value="<%= skill.skill_id %>">
              <% end %>
              <span class="checkmark"></span>
            </label>
          </div>
      </div>



      <div class="selection-container">
        <div class="d-flex justify-content-between">
          <h4>SELECTION</h4>
          <i class="fas fa-eraser" id="clear-all"></i>
        </div>
        <div class="d-flex flex-wrap job-name-container">
          <div id="selection-collection"></div>
        </div>
        <!-- <div class="d-flex justify-content-center"> -->
          <%= submit_tag "SEARCH", class: 'search-btn' %>
          <% end %>
        <!-- </div> -->
        <!-- main form end -->
      </div>
    </div>
</div>

<!-- hidden array for adding skills -->
<% if @pre_selected %>
  <ul class="hidden">
  <% @pre_selected.each do |skill| %>
    <li value="<%= skill %>" class="hidden-skill"></li>\
  <% end %>
  </ul>
  <% end %>
</div>

app/views/vacancies/show.html.erb
<div class="container">
  <!-- title box -->
  <div class="vacancy-container">
    <%= link_to :back, class: 'link_absolute' do %>
    <i class="fas fa-chevron-left"></i>Back
    <% end %>
    <div class="d-flex align-items-center">
      <div class="vacancy-image">
        <%= cl_image_tag @vacancy.photo, height: 140 %>
      </div>
      <div class="vacancy-title">
        <h1><%= @vacancy.title %></h1>
        <h3 >Department: <%= @vacancy.department %></h3>
      </div>
    </div>
  </div>

  <div class="d-flex">
    <div class="left">

      <!-- left side -->

      <!-- description box -->

      <div class="vacancy-info-container">
        <div class="vacancy-info-card">
          <div class="d-flex justify-content-between">
            <h2>Responsibilities</h2>
          </div>
          <div class="job-description">
            <p><%= @vacancy.description.html_safe %></p>
          </div>
        </div>
      </div>


    <!-- Open positions -->

    <div class="job-additional-info">
      <h2>Open Position(s)</h2>
      <div class="openings-info" >
        <p>No current opening for this job</p>
        <div>
          <div class="button btn-message" id="alert-Btn">Alert me</div>
          <!-- Message modal -->
          <div id="AlertModal" class="modal">
            <!-- Modal content -->
            <div class="modal-content-alert">
              <div>
                <p>Get notified when a new <strong><%= @vacancy.title %></strong> position opens.</p>
                <br>
              </div>
              <div class="d-flex justify-content-center">
                <div class="modal-alert-submit">yes please!</div>
                <div class="modal-alert-cancel">no thanks</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>


  <!-- Employee contact -->
  <div class="job-additional-info">
    <h2><%= @vacancy.title %>(s)</h2>
      <% @users.each do |user| %>
        <% unless user == current_user %>
          <div class="employee-contact-chat">
        <%= link_to profile_path(user) do %>
            <div class="employee-contact-info" >
              <%= cl_image_tag user.photo, height: 100, width: 100, crop: :fill, class: 'avatar' %>
              <div>
                <h3><%= user.first_name %> <%= user.last_name %></h3>
                <h4><%= user.location %></h4>
              </div>
            </div>
          <% end %>
            <div class="modal-container">
              <%= render 'shared/employee-modal', user: user %>
            </div>
            </div>
        </div>
      <% end %>
    <% end %>

  </div>
  </div>

  <!-- right side  -->
  <div class="right">

    <!-- Required Skills -->
    <div class="vacancy-skill-card" id="hard">
      <div class="d-flex justify-content-between">
        <h3>Required skills</h3>
      </div>
      <div class="skills-grid-2">
        <% @vacancy_skills.each do |rskill| %>
        <% unless rskill.skill.skill_type == "experience" %>
        <label for="<%= "skill-item-#{rskill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
        url('<%= cl_image_path rskill.skill.photo, height: 300, width: 300, crop: :fill %>')">
        <div class="section">
          <p class="show-profile"><%= rskill.skill.name %></p>

          <!-- Popover -->
            <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
            data-popover-content="#myPopoverContent<%=rskill.id%>"><i class="fas fa-info-circle"></i></a>

            <!-- Content for Popover: -->
            <div id="myPopoverContent<%=rskill.id%>" style="display:none">
              <div class="skill-info">
                <h2><%= rskill.skill.name %></h2>
                <p><%= rskill.skill.description %></p>
              </div>
            </div>

          <div class="overlay">
          </div>
        </div>
      </label>
      <% end %>
      <% end %>
    </div>
  </div>

  <!-- Preferred Skills -->
  <div class="vacancy-skill-card" id="hard">
    <div class="d-flex justify-content-between">
      <h3>Preferred skills</h3>
    </div>
    <div class="skills-grid-2">
      <% @preferred_skills.each do |pskill| %>
        <label for="<%= "skill-item-#{pskill.id}" %>" class="skill-grid-item checkbox hard" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
        url('<%= cl_image_path pskill.skill.photo, height: 300, width: 300, crop: :fill %>')">
        <div class="section">
          <p class="show-profile"><%= pskill.skill.name %></p>

            <!-- Popover -->
              <a class="popover-skill" data-toggle="popover" data-placement="right" title="" data-trigger="hover" data-html="true"
              data-popover-content="#myPopoverContent<%=pskill.id%>"><i class="fas fa-info-circle"></i></a>

              <!-- Content for Popover: -->
              <div id="myPopoverContent<%=pskill.id%>" style="display:none">
                <div class="skill-info">
                  <h2><%= pskill.skill.name %></h2>
                  <p><%= pskill.skill.description %></p>
                </div>
              </div>

        <div class="overlay"></div>
        </div>
        </label>
      <% end %>
    </div>
  </div>

<!-- key experiences -->
      <div class="vacancy-skill-card" id="key">
        <div class="d-flex justify-content-between">
          <h3>Preferred Key Experiences</h3>
        </div>
        <div class="skills-grid-2">

          <% @vacancy_skills.each do |vskill| %>
          <% if vskill.skill.skill_type == "experience" %>
          <label for="<%= "skill-item-#{vskill.id}" %>" class="skill-grid-item checkbox key" style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5)),
          url('<%= cl_image_path vskill.skill.photo, height: 300, width: 300 %>')">

          <div class="section">
            <p class="show-profile"><%= vskill.skill.name %></p>
            <div class="overlay">
            </div>
          </div>
        </label>
        <% end %>
        <% end %>
      </div>
    </div>



</div>

</div>


</div>