config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'


  get 'presearch', to: 'profiles#presearch', as: :presearch
  get 'profiles/search', to: 'profiles#search', as: :profile_search
  patch 'myprofile', to: 'profiles#update', as: :myprofile_update
  get 'myprofile', to: 'profiles#myprofile', as: :myprofile
  get 'profile/develop_hard', to: 'profiles#develop_hard', as: :develop_hard
  get 'profile/develop_soft', to: 'profiles#develop_soft', as: :develop_soft
  get 'profile/develop_key', to: 'profiles#develop_key', as: :develop_key
  get 'vacancies/search', to: 'vacancies#search', as: :vacancy_search
  get 'myprofile/edit_user_skills', to: 'profiles#edit_user_skills', as: :edit_user_skills
  patch 'myprofile/update_user_skills', to: 'profiles#update_user_skills', as: :update_user_skills
  get 'myprofile/edit_develop_skills', to: 'profiles#edit_develop_skills', as: :edit_develop_skills
  patch 'myprofile/update_develop_skills', to: 'profiles#update_develop_skills', as: :update_develop_skills

  post 'message/update', to: 'messages#update_message'

  resources :profiles, only: [:index, :show, :edit, :update]

  resources :vacancies, only: [:index, :show]

  resources :conversations, only: [:index, :create, :show] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end
end

app/views/shared/_employee-modal.html.erb
<div class="button btn-message" id="sendBtn<%= user.id %>" data-id="<%= user.id %>">Send message</div>
<!-- Message modal -->
<div id="sendMessageModal<%= user.id %>" class="modal">
  <!-- Modal content -->
  <div class="modal-content<%= user.id %> modal-content">
    <p><em><%= "Send #{user.first_name} a message..." %></em></p>
    <%= simple_form_for :conversation, url: conversations_path(user_id: user.id), remote: true, method: :post, html: { class: "new_message"} do |form| %>
      <%= form.input :content, label: false, input_html: { id: "message-field-#{user.id}" } %>
      <% form.hidden_field :user_id, value: user %>
      <div class="d-flex">
        <%= form.button :submit, value: 'send', class: "modal-submit-#{user.id} modal-submit" %>
      <% end %>
      <div class="modal-cancel-<%= user.id %> modal-cancel">cancel</div>
      </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer <%= "footer-nomargin" if controller.controller_name == "pages" %>" >
  <div class="us-links">
    <p>Contact us</p>
    <p>About us</p>
  </div>
  <div class="middle-link">
    <p>Recruit.me &copy; MMXIX</p>
  </div>
  <div class="footer-buttons">
    <div class="button-TAC">Terms & Conditions</div>
    <div class="button-FAQ">F.A.Q</div>
  </div>
</div>

app/views/shared/_modal-job-alerts.html.erb
<!-- Button trigger modal -->
<button type="button" class="button" data-toggle="modal" data-target="#exampleModalCenter">
  ALERT
</button>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Job alert</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        You will be notified when a new <strong><%= @vacancy.title %></strong> position opens.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<div class="container">
  <div class="company-detail">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.jpg", class: "company-logo" %>
    <% end %>
    <div id="logo-style">
      <% if current_page?(conversations_path) %>
        <%= link_to root_path do %>
          <span>RECRUIT.me</span><span id="diff-logo">ssenger</span>
        <% end %>
      <% else %>
        <%= link_to "RECRUIT.me", root_path %>
      <% end %>
    </div>
  </div>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
           <%= link_to "POSITIONS", vacancy_search_path, class: "nav-link #{'active' if params[:controller] == "vacancies"}" %>
        </li>
        <li class="nav-item">
          <%= link_to "CANDIDATES", profile_search_path, class: "nav-link  #{'active' if params[:controller] == "profiles"}" if current_user.is_manager? %>
        </li>
        <li>

        <!-- logic to find new mail -->
        <% mail_classes = 'fa fa-envelope' %>

        <% if !current_page?(conversations_path) %>
          <% my_conversations = Conversation.where(recipient: current_user).or(Conversation.where(sender: current_user)) %>
          <% if my_conversations.length > 0 %>
            <% my_conversations.each do |conversation| %>
            <% r_Messages = conversation.messages.where.not(user: current_user) %>
              <% if r_Messages.count > 0 %>
                <% r_Messages.each do |message| %>
                  <% if message.read == false %>
                    <% mail_classes = 'fa fa-envelope mail-active' %>
                  <% end %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>

          <%= link_to conversations_path do %>
            <i class="<%= mail_classes %>" aria-hidden="true"></i>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <img class="avatar avatar-navbar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= cl_image_path current_user.photo, height: 200, width: 200, crop: :fill %>" />
          <% else %>
            <img class="avatar avatar-navbar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= image_path 'avatar-blank.jpg' %>" />
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My profile", myprofile_path, class: "dropdown-item" %>
            <%= link_to "Inbox", conversations_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>
</div>